// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzoogdzffyryecdjfhnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6b29nZHpmZnlyeWVjZGpmaG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDk4NzksImV4cCI6MjA1MzY4NTg3OX0.fWTW-kSIVyNQiv7HRxpWtzX9KJnfDp_pqRTp-sbbN4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);